In [ ]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import f1_score, confusion_matrix
from sklearn import preprocessing
import matplotlib.pyplot as plt
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import f1_score, confusion_matrix, accuracy_score, precision_score
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.preprocessing import LabelEncoder

In [ ]:
property_sale = pd.read_csv("2002-2018-property-sales-data.csv")
property_sale.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34523 entries, 0 to 34522
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PropType      34520 non-null  object
 1   Taxkey        34523 non-null  int64
 2   Address       34523 non-null  object
 3   CondoProject  6656 non-null   object
 4   District      34523 non-null  int64
 5   Nbhd          34523 non-null  int64
 6   Style         34517 non-null  object
 7   Extwall       24624 non-null  object
 8   Stories       34523 non-null  float64
 9   Year_Built    34523 non-null  int64
 10  Nr_of_rms     34523 non-null  int64
 11  Fin_sqft      34523 non-null  int64
 12  Units         34523 non-null  int64
 13  Bdrms         34523 non-null  int64
 14  Fbath         34523 non-null  int64
 15  Hbath         34523 non-null  int64
 16  Lotsize       34523 non-null  int64
 17  Sale_date     34523 non-null  object
 18  Sale_price    34523 non-null  int64
dtypes: float64(1), int64(12), object(6)
memory usage: 5.0+ MB

In [ ]:
print("Valores duplicados: ", property_sale.duplicated().sum())
duplicate = property_sale[property_sale.duplicated()]
duplicate

Valores duplicados:  41

,PropType,Taxkey,Address,CondoProject,District,Nbhd,Style,Extwall,Stories,Year_Built,Nr_of_rms,Fin_sqft,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_date,Sale_price
451,Commercial,4000503000,2207 W WISCONSIN AV,NaN,4,6270,Office Building - Multi Story ( Ofc & Apt),NaN,1.0,1969,0,6650,1,0,0,0,14438,2004-04,399000
613,Lg Apartment,5549987100,3760 S 43RD ST,"10: 1-Br ,8: 2-Br ,3: 3-Br",11,6981,"Apartment: 10: 1-Br ,8: 2-Br ,3: 3-Br Units",NaN,2.0,1970,0,21000,1,0,0,0,0,2004-11,1050000
661,NaN,30131000,9434 N 107TH ST,NaN,9,6300,Office Building - 1 Story,NaN,1.0,1978,0,20600,1,0,0,0,75359,2004-12,740000
2188,Vacant Land,6900403100,6020 S 27TH ST,NaN,13,4860,**,NaN,0.0,0,0,0,0,0,0,0,19780,2009-03,82001
2189,Vacant Land,6900403100,6020 S 27TH ST,NaN,13,4860,**,NaN,0.0,0,0,0,0,0,0,0,19780,2009-03,82001
2380,Residential,1750345200,5853 N 74TH ST,NaN,2,980,Ranch,Aluminum / Vinyl,1.0,1952,0,969,1,2,1,0,4800,2009-05,5000
2382,Residential,1750345200,5853 N 74TH ST,NaN,2,980,Ranch,Aluminum / Vinyl,1.0,1952,0,969,1,2,1,0,4800,2009-05,5000
2388,Residential,2790304000,3482 N FREDERICK AV,NaN,3,3060,Colonial,Brick,1.5,1923,0,2351,1,4,2,1,7050,2009-05,370000
2925,Condominium,3541536000,1905 N WATER ST,RIVERBRIDGE,3,5964,APARTMENT,NaN,1.0,2005,4,1262,1,1,1,0,0,2009-06,195000
3127,Residential,5260633000,9014 W BURDICK AV,NaN,11,4340,Ranch,Brick,1.0,1959,0,1022,1,3,1,1,7500,2009-07,82000
3179,Residential,5000223000,931 E CONWAY ST,NaN,14,4910,Cottage,Aluminum / Vinyl,1.0,1898,0,810,1,2,1,0,1350,2009-07,75000
3429,Residential,3050524000,2738 N 72ND ST,NaN,10,1980,Tudor,Stone,1.5,1931,0,1837,1,3,1,1,6192,2009-08,220000
3567,Condominium,3592132000,1313 N FRANKLIN PL,BREAKWATER CONDOS,4,5811,HI-RISE,NaN,0.0,2009,0,1108,1,1,1,1,0,2009-08,216216
3736,Residential,2890134000,3425 N 54TH ST,NaN,10,1850,Duplex N/S,Stone,2.0,1945,0,2026,2,4,2,0,5200,2009-09,120000
4576,Residential,3090361000,2870 N 29TH ST,NaN,15,2950,Duplex O/S,Aluminum / Vinyl,2.0,1914,0,2536,2,6,2,0,3750,2009-11,12000
4725,Residential,4340550000,1308 S LAYTON BL,NaN,8,4000,Colonial,Frame,2.0,1922,0,1824,1,4,1,1,5590,2009-12,101000
5140,Condominium,3531873000,2145 N 1ST ST,BREW CITY PILSNER CONDOMINIUM,6,5719,APARTMENT,NaN,2.0,1992,5,1852,1,3,2,1,0,2010-03,133000
5225,Residential,3031148000,7926 W LORRAINE PL,NaN,5,2080,Ranch,Brick,1.0,1947,0,952,1,2,2,0,5040,2010-04,146500
5520,Residential,4590063000,2012 W ORCHARD ST,NaN,8,4100,Residence O/S,Aluminum / Vinyl,1.0,1892,0,1523,1,4,2,0,4200,2010-05,80000
5635,Residential,5040490000,2911 S CALIFORNIA ST,NaN,14,4500,Ranch,Aluminum / Vinyl,1.0,1953,0,1100,1,3,1,1,6000,2010-05,172500
6282,Residential,3090193000,3023 N 29TH ST,NaN,7,2960,Milwaukee Bungalow,Aluminum / Vinyl,1.5,1923,0,2024,1,5,2,0,3600,2010-09,35000
6760,Commercial,1569984110,5135 W MILL RD,NaN,9,6216,Parking Lot,NaN,0.0,0,0,0,1,0,0,0,14244,2010-12,22500
7910,Commercial,2170225120,10722 W HAMPTON AV,NaN,5,6212,Strip Shopping Center,NaN,1.0,1966,0,10630,1,0,0,0,30000,2011-08,382500
9039,Lg Apartment,2749985000,1002 E VIENNA AV,4: 2-Br,6,6761,Apartment: 4: 2-Br Units,NaN,2.0,1952,0,3884,1,0,0,0,6900,2012-04,215000
11260,Residential,2880367000,3347 N 47TH ST,NaN,7,1840,Milwaukee Bungalow,Brick,1.0,1936,0,1549,1,4,2,0,5125,2013-05,106000
11844,Residential,4219951000,5919 W MAIN ST,NaN,10,2710,Milwaukee Bungalow,Aluminum / Vinyl,1.0,1930,0,1491,1,3,1,0,6375,2013-07,90000
12628,Residential,2250263000,4329 N 74TH ST,NaN,2,1480,Cape Cod,Brick,1.0,1948,0,1250,1,3,1,1,4960,2013-10,83000
13385,Condominium,3930839100,825 N PROSPECT AV,UNIVERSITY CLUB TOWER CONDOS,4,5994,APARTMENT,NaN,1.0,2007,11,6411,1,3,4,2,0,2014-01,2600000
16147,Residential,3280754000,2554 N 46TH ST,NaN,15,2520,Milwaukee Bungalow,Aluminum / Vinyl,1.0,1919,0,1517,1,3,2,0,5000,2014-12,95000
17450,Residential,1710567000,5690 N 37TH ST,NaN,1,900,Residence O/S,Aluminum / Vinyl,1.0,1924,0,810,1,2,1,0,4800,2015-06,34050
17485,Residential,3160207000,3002 N PROSPECT AV,NaN,3,3160,Residence O/S,Brick,2.0,1910,0,2694,1,5,2,1,4080,2015-06,295000
18085,Residential,4901212000,2636 S 65TH ST,NaN,11,4240,Cape Cod,Block,1.0,1949,0,1406,1,4,2,0,4900,2015-07,159500
19172,Residential,1420152000,7809 W GREEN TREE RD,NaN,9,480,Ranch,Aluminum / Vinyl,1.0,1960,0,936,1,3,1,0,6360,2015-10,78000
21775,Residential,4670349000,1937 S 5TH ST,NaN,12,4120,Duplex O/S,Aluminum / Vinyl,1.5,1910,0,1846,2,6,2,0,2880,2016-06,63000
23246,Residential,5959967000,230 W MARTIN LA,NaN,13,4740,Ranch,Brick,1.0,1958,0,990,1,3,1,0,7650,2016-09,156000
25329,Residential,3470101000,1756 N HI MOUNT BL,NaN,10,2580,Residence O/S,Masonry / Frame,2.0,1915,0,2728,1,5,2,1,8100,2017-04,335000
28294,Residential,5520210000,3829 S 24TH ST,NaN,13,4360,Cape Cod,Aluminum / Vinyl,1.0,1954,0,798,1,2,1,0,5194,2017-10,120000
28547,Residential,2871501000,3457 N 39TH ST,NaN,7,1740,Dplx Bungalow,Brick,1.5,1919,0,2391,2,4,2,0,7360,2017-11,92000
29074,Residential,5360272000,3322 S 8TH ST,NaN,14,4520,Dplx Bungalow,Aluminum / Vinyl,1.5,1925,0,2005,2,4,2,0,4880,2017-12,65500
29414,Condominium,3601561000,1658 N JACKSON ST,JACKSON STREET TOWNHOMES,3,5661,TOWNHOUSE,NaN,2.0,2005,5,2395,1,3,2,1,0,2018-01,217000
29689,Condominium,2812752000,3059 N WEIL ST,HI-FI LOFTS CONDOMINIUMS,3,5720,APARTMENT,NaN,1.0,1904,3,982,1,1,1,0,0,2018-02,137000

In [ ]:
property_sale = property_sale.drop_duplicates()

In [ ]:
print("Valores duplicados: ", property_sale.duplicated().sum())
duplicate = property_sale[property_sale.duplicated()]
duplicate

Valores duplicados:  0

Empty DataFrame
Columns: [PropType, Taxkey, Address, CondoProject, District, Nbhd, Style, Extwall, Stories, Year_Built, Nr_of_rms, Fin_sqft, Units, Bdrms, Fbath, Hbath, Lotsize, Sale_date, Sale_price]
Index: []

In [ ]:
colunas_com_valores_faltantes = property_sale.columns[property_sale.isna().any()].tolist()

print("Colunas com valores faltantes:", colunas_com_valores_faltantes)

Colunas com valores faltantes: ['PropType', 'CondoProject', 'Style', 'Extwall']

In [ ]:
property_sale = property_sale.drop(columns=['Address', 'CondoProject', 'Taxkey', 'Nbhd'])

In [ ]:
print("Valores faltantes: ", property_sale.isnull().sum().sum())

Valores faltantes:  9893

In [ ]:
property_sale.fillna('0', inplace=True)

pd.options.display.max_columns = None
property_sale

,PropType,District,Style,Extwall,Stories,Year_Built,Nr_of_rms,Fin_sqft,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_date,Sale_price
0,Commercial,6,Commercial Exempt,0,2.0,1880,0,1840,1,0,0,0,12750,2002-01,15900
1,Commercial,3,Mansions With Commercial Usage,0,2.0,1876,0,6377,1,0,0,0,11840,2002-01,850000
2,Commercial,10,Service Building,0,1.0,1954,0,5022,1,0,0,0,9700,2002-01,119000
3,Commercial,1,"Store Bldg - Multi Story (Store & Apt, Store & O",0,2.0,1955,0,6420,1,0,0,0,8792,2002-01,210000
4,Commercial,15,"Store Bldg - Multi Story (Store & Apt, Store & O",0,2.0,1909,0,5956,1,0,0,0,4840,2002-01,48500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34518,Commercial,6,Warehouse Building - 1 Story,0,1.0,1949,0,4800,1,0,0,0,9000,2018-12,165000
34519,Vacant Land,1,Commercial Land,0,0.0,0,0,0,1,0,0,0,7800,2018-12,3900
34520,Vacant Land,13,Commercial Land,0,0.0,0,0,0,1,0,0,0,152286,2018-12,100000
34521,Vacant Land,5,**,0,0.0,0,0,0,0,0,0,0,8925,2018-12,362400
34522,Vacant Land,3,**,0,0.0,0,0,0,0,0,0,0,5400,2018-12,91000

In [ ]:
print("Valores duplicados: ", property_sale.duplicated().sum())
duplicate = property_sale[property_sale.duplicated()]
duplicate

Valores duplicados:  17

,PropType,District,Style,Extwall,Stories,Year_Built,Nr_of_rms,Fin_sqft,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_date,Sale_price
3865,Condominium,9,APARTMENT,0,1.0,1999,5,1125,1,2,2,0,0,2009-09,109900
3866,Condominium,9,APARTMENT,0,1.0,1999,5,1125,1,2,2,0,0,2009-09,109900
6753,Lg Apartment,5,Apartment: 4: 2-Br Units,0,2.0,1956,0,3660,1,0,0,0,10800,2010-12,378000
6953,Residential,2,Duplex N/S,Aluminum / Vinyl,2.0,1973,0,2340,2,6,2,2,5000,2011-03,40000
10508,Lg Apartment,14,Apartment: 8: 1-Br Units,0,2.0,1928,0,6152,1,0,0,0,6534,2012-12,397500
10747,Condominium,4,APARTMENT,0,1.0,1990,4,733,1,1,1,0,0,2013-02,132500
11684,Condominium,4,Apartment,0,1.0,2008,4,708,1,1,1,0,0,2013-06,105000
14222,Condominium,5,APARTMENT,0,1.0,1974,4,863,1,1,1,0,0,2014-05,29900
15727,Condominium,4,APARTMENT,0,2.0,1901,4,980,1,2,1,1,0,2014-10,170000
18257,Condominium,3,APARTMENT,0,1.0,1969,3,643,1,1,1,0,0,2015-07,86500
22472,Condominium,9,TOWN HOUSE,0,2.5,1970,5,1054,1,3,1,1,0,2016-07,15000
24045,Lg Apartment,11,Apartment: 8: 1-Br Units,0,2.0,1952,0,4448,1,0,0,0,9625,2016-11,324000
29712,Condominium,9,TOWN HOUSE,0,2.5,1970,5,1054,1,3,1,1,0,2018-02,18250
30649,Lg Apartment,11,Apartment: 8: 1-Br Units,0,2.0,1952,0,4448,1,0,0,0,10750,2018-04,1230000
30650,Lg Apartment,11,Apartment: 8: 1-Br Units,0,2.0,1952,0,4448,1,0,0,0,10750,2018-04,1230000
32293,Condominium,9,TOWN HOUSE,0,2.5,1970,5,1054,1,3,1,1,0,2018-07,22000
33694,Condominium,9,TOWN HOUSE,0,2.5,1970,5,1054,1,3,1,1,0,2018-10,20000

In [ ]:
property_sale = property_sale.drop_duplicates()

In [ ]:
print("Valores duplicados: ", property_sale.duplicated().sum())
duplicate = property_sale[property_sale.duplicated()]
duplicate

Valores duplicados:  0

Empty DataFrame
Columns: [PropType, District, Style, Extwall, Stories, Year_Built, Nr_of_rms, Fin_sqft, Units, Bdrms, Fbath, Hbath, Lotsize, Sale_date, Sale_price]
Index: []

In [ ]:
property_sale['PropType'].value_counts()

PropType
Residential     24606
Condominium      5698
Commercial       2919
Lg Apartment     1010
Vacant Land       230
0                   2
Name: count, dtype: int64

In [ ]:
property_sale = property_sale.drop(columns=['Style','Sale_date','District'])

In [ ]:
property_sale = property_sale[property_sale['Lotsize'] != 0]

In [ ]:
property_sale = property_sale[property_sale['PropType'] != 0]

In [ ]:
property_sale['PropType'].value_counts()

PropType
Residential     24459
Commercial       2917
Lg Apartment      949
Vacant Land       230
0                   2
Name: count, dtype: int64

In [ ]:
bins = [0, 200000, 300000, 600000, float('inf')]
labels = ['Econômico', 'Conforto', 'Luxo', 'Superluxo']

property_sale['Sale_price_class'] = pd.cut(property_sale['Sale_price'], bins=bins, labels=labels, right=False)

property_sale.head()

,PropType,Extwall,Stories,Year_Built,Nr_of_rms,Fin_sqft,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_price,Sale_price_class
0,Commercial,0,2.0,1880,0,1840,1,0,0,0,12750,15900,Econômico
1,Commercial,0,2.0,1876,0,6377,1,0,0,0,11840,850000,Superluxo
2,Commercial,0,1.0,1954,0,5022,1,0,0,0,9700,119000,Econômico
3,Commercial,0,2.0,1955,0,6420,1,0,0,0,8792,210000,Conforto
4,Commercial,0,2.0,1909,0,5956,1,0,0,0,4840,48500,Econômico

In [ ]:
property_sale['Sale_price_class'].value_counts()

Sale_price_class
Econômico    23116
Conforto      3075
Luxo          1372
Superluxo      994
Name: count, dtype: int64

In [ ]:
df = property_sale[~property_sale['PropType'].isin(['Commercial', 'Lg Apartment', 'Vacant Land', '0'])]
property_sale = df

property_sale.head()

,PropType,Extwall,Stories,Year_Built,Nr_of_rms,Fin_sqft,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_price,Sale_price_class
10,Residential,Frame,2.0,1913,0,3476,4,9,1,0,5040,42000,Econômico
51,Residential,Frame,2.0,1897,0,1992,4,2,2,0,2880,145000,Econômico
67,Residential,Frame,2.0,1907,0,2339,6,0,1,0,3185,30000,Econômico
116,Residential,Frame,2.0,1890,0,2329,4,4,1,0,5781,66500,Econômico
134,Residential,Stone,2.5,1891,0,7450,2,7,6,0,15600,150500,Econômico

In [ ]:
property_sale['PropType'].value_counts()

PropType
Residential    24459
Name: count, dtype: int64

In [ ]:
property_sale_class = property_sale.drop(columns=['Sale_price'])
property_sale_class = property_sale_class.drop(columns=['PropType'])

In [ ]:
property_sale_class.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24459 entries, 10 to 34449
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Extwall           24459 non-null  object
 1   Stories           24459 non-null  float64
 2   Year_Built        24459 non-null  int64
 3   Nr_of_rms         24459 non-null  int64
 4   Fin_sqft          24459 non-null  int64
 5   Units             24459 non-null  int64
 6   Bdrms             24459 non-null  int64
 7   Fbath             24459 non-null  int64
 8   Hbath             24459 non-null  int64
 9   Lotsize           24459 non-null  int64
 10  Sale_price_class  24459 non-null  category
dtypes: category(1), float64(1), int64(8), object(1)
memory usage: 2.1+ MB

In [ ]:
le_extwall = LabelEncoder()

property_sale_class['Extwall'] = le_extwall.fit_transform(property_sale_class['Extwall'])

mapeamento_extwall = dict(zip(le_extwall.classes_, le_extwall.transform(le_extwall.classes_)))

print("Mapeamento para a coluna Extwall:")
for valor_original, valor_codificado in mapeamento_extwall.items():
    print(f"  {valor_original} --> {valor_codificado}")

Mapeamento para a coluna Extwall:
  0 --> 0
  Aluminum / Vinyl --> 1
  Block --> 2
  Brick --> 3
  Fiber-Cement --> 4
  Frame --> 5
  Masonry / Frame --> 6
  Prem Wood --> 7
  Stone --> 8
  Stucco --> 9

In [ ]:
property_sale_class['Sale_price_class'].value_counts()

Sale_price_class
Econômico    21292
Conforto      2398
Luxo           652
Superluxo      117
Name: count, dtype: int64

In [ ]:
order = ['Econômico', 'Conforto', 'Luxo', 'Superluxo']

property_sale_class['Sale_price_class'] = pd.Categorical(
    property_sale_class['Sale_price_class'],
    categories=order,
    ordered=True
)

property_sale_class['Sale_price_class'] = property_sale_class['Sale_price_class'].cat.codes

In [ ]:
property_sale_class['Sale_price_class'].value_counts()

Sale_price_class
0    21292
1     2398
2      652
3      117
Name: count, dtype: int64

In [ ]:
property_sale_class = property_sale_class[property_sale_class['Year_Built'] != 0]
property_sale_class = property_sale_class[property_sale_class['Fin_sqft'] != 0]
property_sale_class = property_sale_class[property_sale_class['Lotsize'] != 0]
property_sale_class = property_sale_class[property_sale_class['Stories'] != 0]
property_sale_class = property_sale_class[property_sale_class['Units'] != 0]
property_sale_class = property_sale_class.drop(columns=['Nr_of_rms'])

In [ ]:
corr = property_sale_class.corr()
corr.style.background_gradient(cmap = 'coolwarm')

In [ ]:
property_sale_class = property_sale_class.drop(columns=['Fbath', 'Units', 'Stories'])
corr = property_sale_class.corr()
corr.style.background_gradient(cmap = 'coolwarm')

In [ ]:
property_sale_class['Sale_price_class'].value_counts()

Sale_price_class
0    21285
1     2397
2      651
3      117
Name: count, dtype: int64

In [ ]:
qtd_splits = 10
seed = 35
vc_estratificada = StratifiedKFold(n_splits=qtd_splits, shuffle=True, random_state=seed)

X = property_sale_class.drop(columns=['Sale_price_class'])
y = property_sale_class['Sale_price_class']

In [ ]:
num_arvores = 100

f1_scores = []
matriz_confusao = []
cv_scores_train = []
cv_scores_test = []
accuracy_scores = []
precision_scores = []

rf = RandomForestClassifier(n_estimators=num_arvores, random_state=seed)

for train_index, test_index in vc_estratificada.split(X, y):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    rf.fit(X_train, y_train)

    cv_score_train = cross_val_score(rf, X_train, y_train, cv=qtd_splits)
    cv_score_test = cross_val_score(rf, X_test, y_test, cv=qtd_splits)
    cv_scores_train.append(np.mean(cv_score_train))
    cv_scores_test.append(np.mean(cv_score_test))

    predicoes = rf.predict(X_test)

    f1 = f1_score(y_test, predicoes, average='weighted')
    f1_scores.append(f1)

    accuracy = accuracy_score(y_test, predicoes)
    accuracy_scores.append(accuracy)

    precision = precision_score(y_test, predicoes, average='weighted')
    precision_scores.append(precision)

    matriz_confusao_fold = confusion_matrix(y_test, predicoes)
    matriz_confusao.append(matriz_confusao_fold)

f1_media = np.mean(f1_scores)
cv_score_train_media = np.mean(cv_scores_train)
cv_score_test_media = np.mean(cv_scores_test)
accuracy_media = np.mean(accuracy_scores)
precision_media = np.mean(precision_scores)

print("F1-score médio: {:.2f}".format(round(f1_media, 2)))
print("CV score médio no conjunto de treinamento: {:.2f}".format(round(cv_score_train_media, 2)))
print("CV score médio no conjunto de teste: {:.2f}".format(round(cv_score_test_media, 2)))
print(f"Acurácia média: {accuracy_media:.2f}")
print(f"Precisão média: {precision_media:.2f}")

matriz_final = sum(matriz_confusao)
print("\nMatriz de Confusão Final:")
print(matriz_final)

F1-score médio: 0.88
CV score médio no conjunto de treinamento: 0.89
CV score médio no conjunto de teste: 0.88
Acurácia média: 0.89
Precisão média: 0.88

Matriz de Confusão Final:
[[20743   465    73     4]
 [ 1545   742   106     4]
 [  177   137   312    25]
 [    0     1    38    78]]